### ISSUE TITLE
Forecast period

### ISSUE THREAD

**Issue by EdjOne** [G6EJD/LilyGo-EPD-4-7-OWM-Weather-Display#9]
Hi, great project. I love it:)

Anyhow, how to reduce forecast period, we have 3 hours period now, but it's not so convenient, like now, i have 22:05 (last update) local time, and the nearest forecast 03:00, so I have a gap 5 hours.... 
Any idea?

**Comment by fdufnews** [comment]
I am a bit surprised, I have no hole in the forecast (look at the picture)
![IMG_20210329_220653](https://user-images.githubusercontent.com/4077715/112894952-cf4bfa80-90dc-11eb-8004-861de63f70f1.jpg) The update is at 22:05, the next forecast at 1:00 and the next one at 4:00:
; the 3 hour step is the step of the forecast sent by OpenWeatherMap. There are no way to change the step.

**Comment by EdjOne** [comment]
![IMG_20210329_222018](https://user-images.githubusercontent.com/54913815/112897209-ffe56180-90e7-11eb-8911-94a9d2e19bbd.jpg)
You can check my photo :)))

**Comment by EdjOne** [comment]
Also, i have checked API of OWM, they transmit wf hourly too. Have to not exclude=hourly in the API request, but i don't know how to implement )

**Comment by G6EJD** [comment]
Your in a transitional period when open weather map send no interim data, the minimum step is 3-hours, although you should see 00:00 forecast then 03:00, but why is it missed. Actually in the very latest version I’ve dropped the 8 periods of 3–hours and changed it to example:
09:00 12:00 15:00 then today is Monday so the weather at 09:00 on Tuesday, Wednesday, Thursday, Friday and Saturday.
Still being tested because it was working but now OWM have changed their reference times to 01:00, 04:00, 07:00, 10:00 so shifted with the recent DST shift, I don’t understand why they don’t use UTC. Also I’ve noted that in different time zones the reference periods are different again but there’s no documentation that explains why! Sone are earlier sone later, it may well be this time of year when DST is being implemented in March for example 

Regards

David

**Comment by G6EJD** [comment]
Correct there is no way to change the step, the best you could do is interpolate the readings either side of maybe the centre and guess the forecast, buts that’s as good as it gets!

Regards

David

**Comment by G6EJD** [comment]
Looks ok to me, do t forget it’s just displaying OWM data no manipulation of data

Regards

David

**Comment by G6EJD** [comment]
With huge difficulty as the amount of memory required is already huge for 3-hours, not the end result but reading in the data abs deciding it even with a streaming solution it requires 60K of RAM

Regards

David

**Comment by EdjOne** [comment]
So, if we get hourly data, can't use it? I'm not hacker, so can ask stupid questions.

**Comment by EdjOne** [comment]
Also, you says i have to see 00:00 forecast, above picture has 01:00, my is a 03:00. So, one code, different display...

**Comment by EdjOne** [comment]
And one more question, if i translate lang file to russian, does some extra modification of main code required?

**Comment by G6EJD** [comment]
If you go to the credentials file and enter your own key to the one-call example, your lat/Lon and remove the exclusions and then click on the link you’ll see just how much data is returned it is huge, pages and pages of complex JSON to decode.

**Comment by G6EJD** [comment]
> And one more question, if i translate lang file to russian, does some extra modification of main code required?
No just the ‘lang_cc.h’file content to match your language fonts not supported

**Comment by EdjOne** [comment]
I have tried it, i know, but i not understand its too much or not )))

**Comment by EdjOne** [comment]
> > And one more question, if i translate lang file to russian, does some extra modification of main code required?
> > No just the ‘lang_cc.h’file content to match your language fonts not supported

So, need to do something with fonts, I don't how to :(

**Comment by G6EJD** [comment]
The problem was that OWM did not shift the forecast times by the time zone, they were all in UTC, so the timezone offset had to be added to correct it now, but now I see they are shifting the forecast times periods by timezone offset. This makes it quite confusing. Especially as they never seem to publish any changes.
